services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $host: "%sinch.host%"
            $key: "%sinch.key%"
            $secret: "%sinch.secret%"
            $from: "%sinch.from%"

    Fresh\SinchBundle\Controller\:
        resource: '../../Controller/'
        tags:
            - 'controller.service_arguments'

    Fresh\SinchBundle\Service\Sinch:
        class: Fresh\SinchBundle\Service\Sinch
