parameters:
    sinch.service.class: Fresh\SinchBundle\Service\SinchService

services:
    sinch:
        class: "%sinch.service.class%"
        arguments:
            - "%sinch.host%"
            - "%sinch.key%"
            - "%sinch.secret%"
