parameters:
    sinch.controller.class: Fresh\SinchBundle\Controller\SinchController
    sinch.service.class: Fresh\SinchBundle\Service\SinchService

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $host: "%sinch.host%"
            $key: "%sinch.key%"
            $secret: "%sinch.secret%"
            $from: "%sinch.from%"

    Fresh\SinchBundle\Controller\:
        resource: '../../Controller/'
        tags:
            - 'controller.service_arguments'

    Fresh\SinchBundle\Service\SinchService:
        class: Fresh\SinchBundle\Service\SinchService
