language: php
sudo: false

php:
    - 5.6
    - 7.0

before_script:
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --ignore=vendor --standard=psr2
    - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        - genvaldartem@gmail.com
