language: php
sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=3.0.*

allow_failures:
  - php: hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --ignore=vendor --standard=./vendor/escapestudios/symfony2-coding-standard/Symfony2
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
  email:
    - genvaldartem@gmail.com
